site_name: The GUAQ Initiative
site_description: Documentation for the GUAQ Project
site_url: https://guaqteam.github.io/docs/

nav:
  - Device Configuration: configuration.md

theme:
  name: 'material'
  palette:
    primary: 'Blue Grey'
    accent: 'Green'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/guaqteam'
    - type: 'instagram'
      link: 'https://instagram.com/guaqteam'
