site_name: GUAQ Documentation
nav:
  - Home: index.md
  - Device Configuration: configuration.md
theme:
  name: 'material'
  palette:
    primary: 'Blue Grey'
    accent: 'Green'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
